version: "3"
services:
    fashion-campus-api:
        container_name: "fashion-campus-api"
        build: "."
        image: "michaelrk02/fashion-campus-api"
        ports:
            - "8000:8000"
        environment:
            POSTGRES_HOST: "${POSTGRES_HOST}"
            POSTGRES_PORT: "${POSTGRES_PORT}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
            APP_KEY: "${APP_KEY}"
            DATABASE_VERBOSE: "${DATABASE_VERBOSE}"
        volumes:
            - "./blob:/app/FashionCampus/blob"
            - "./nn/data:/app/FashionCampus/nn/data"
        depends_on:
            - "fashion-campus-db"
        networks:
            - "fashion-campus"
    fashion-campus-db:
        container_name: "fashion-campus-db"
        build: "database"
        image: "michaelrk02/fashion-campus-db"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - "./database/storage:/var/lib/postgresql/data"
        networks:
            - "fashion-campus"

networks:
    fashion-campus:
